# Generated by Django 2.1.5 on 2019-03-06 01:05

from django.db import migrations, models
import django.db.models.deletion
import django_mysql.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tweet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=30)),
                ('text', models.CharField(max_length=280)),
                ('in_reply_to_status_id', models.CharField(max_length=30)),
                ('in_reply_to_user_id', models.CharField(max_length=30)),
                ('in_reply_to_screen_name', models.CharField(max_length=300)),
                ('geo', models.CharField(max_length=300)),
                ('coordinates', models.CharField(max_length=300)),
                ('place', models.CharField(max_length=30)),
                ('quoted_status_id', models.CharField(max_length=30)),
                ('quoted_status_permanlink', models.CharField(max_length=300)),
                ('quote_count', models.IntegerField(default=0)),
                ('reply_count', models.IntegerField(default=0)),
                ('retweet_count', models.IntegerField(default=0)),
                ('favorite_count', models.IntegerField(default=0)),
                ('entities', django_mysql.models.JSONField(default=dict)),
                ('quoted_staus', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.Tweet')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_str', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('screen_name', models.CharField(max_length=30)),
                ('location', models.CharField(max_length=30)),
                ('url', models.CharField(max_length=30)),
                ('description', models.CharField(max_length=30)),
                ('verified', models.BooleanField(default=False)),
                ('followers', models.IntegerField(default=0)),
                ('statuses_count', models.IntegerField(default=0)),
                ('created_at', models.CharField(max_length=30)),
                ('profile_image_url', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='tweet',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='app.User'),
        ),
    ]
