# Generated by Django 2.1.5 on 2019-03-06 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20190305_2304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_image_url',
            field=models.CharField(max_length=3000),
        ),
    ]
