# Generated by Django 2.1.5 on 2019-03-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20190305_2306'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_screen_name',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_status_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='in_reply_to_user_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='quoted_status_permanlink',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
