# Generated by Django 2.1.5 on 2019-03-06 02:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20190305_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='coordinates',
            field=models.CharField(max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='tweet',
            name='quoted_status_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
