# Generated by Django 2.1.5 on 2019-03-06 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20190305_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='url',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
