# Generated by Django 2.1.5 on 2019-03-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20190305_2327'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
