# Generated by Django 2.1.5 on 2019-03-06 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_auto_20190305_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='quoted_status_permanlink',
            new_name='quoted_status_permalink',
        ),
    ]
