# Generated by Django 2.1.5 on 2019-03-06 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20190305_2331'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='tag',
            field=models.CharField(default=None, max_length=300),
        ),
    ]
