# Generated by Django 2.1.5 on 2019-03-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20190305_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='place',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
