# Generated by Django 2.1.5 on 2019-03-06 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20190305_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='place',
            field=models.CharField(max_length=3000, null=True),
        ),
    ]
