# Generated by Django 2.1.5 on 2019-03-06 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20190305_2351'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='credated_at',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
