# Generated by Django 2.1.5 on 2019-03-06 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20190306_0042'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='credated_at',
            new_name='created_at',
        ),
    ]
